#!/bin/bash

#----colors----
red='\033[1;91m'
green='\033[1;92m'
yellow='\033[1;93m'
blue='\033[1;94m'
purple='\033[1;95m'
cyan='\033[1;96m'
white='\033[1;97m'

#--cmmd---
un=$(uname)
uid=$(whoami)
unm=$(uname -m)
hos=$(hostname)
line=$(echo '=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=')
date=$(date)
clear
echo

echo "$red[!] \033[38;5;202m Checking Requirements...."
echo
sleep 0.4
echo "$line" | lolcat
echo
sleep 0.2
echo "$red[!]:\033[38;5;202m [Checking Dependencies]:"
echo
sleep 0.5
echo "$green[✔]:[ Distro ]: $cyan $un"
echo
sleep 1.3
echo "$green[✔]:[ Architecture ]: $cyan $unm"
sleep 1.9
echo
echo "$green[✔]:[ Date ]: $cyan $date"
sleep 1.2
echo
   if [ -d /data/data/com.termux/files/home/metasploit-framework/ ]
   then
         echo "$green[✔]:[ Metasploit ]: $cyan Installed !"
   else
         echo "$green[x]:[ Metasploit ]: $red NOT Installed ! "
         echo "[ $red For Using This Tool you Must Install Metasploit ] "
         apt install metasploit
   fi
echo
sleep 0.5
   if [ -f /data/data/com.termux/files/home/metasploit-framework/msfvenom ];
   then
        echo "$green[✔]:[ Msfvenom ]: $cyan Found !"
   else
        echo "$green[x]:[ Msfvenom ]: $red NOT Found ! "
  fi
echo
sleep 0.3
   if [ -f /data/data/com.termux/files/home/metasploit-framework/msfconsole ];
   then 
        echo "$green[✔]:[ Msfconsole ]: $cyan Found !"
   else
        echo "$green[x]:[ Msfconsole ]: $red NOT Found ! "
   fi
sleep 1.9
echo
   if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; 
   then
         echo "$green[✔]:[ Internet ]: $cyan Connected !" 
   else
         echo "$green[x]:[ Internet ]: $red NOT Connected !"
   fi
echo
sleep 2
echo "$green[✔]:[ User ID ]: $cyan $uid"
sleep 1.5
echo
echo "$green[✔]:[ Hostname ]: $cyan $hos"
echo
sleep 1.3

    if [ -f /data/data/com.termux/files/usr/bin/ruby ]
    then
       echo "$green[✔]:[ Ruby ]: $cyan Found !" 
    else
       echo "$green[✔]:[ Ruby ]: $red NOT Found !"
       echo 
       echo "$green Installing Ruby.... "
       pkg install ruby
       echo
    fi
sleep 1.2
echo
    if [ -f /data/data/com.termux/files/usr/bin/lolcat ]
    then
        echo "$green[✔]:[ Lolcat ]: $cyan Found !"
    else
       echo "$green[✔]:[ Lolcat ]: $red NOT Found !"
       echo
       echo "$green Installing Lolcat...."
       gem install lolcat
       echo
    fi
echo 
sleep 0.3
echo "$purple[+] $green Starting Venomsploit........."
sleep 5
echo
